---
- hosts: webservers
  become: yes
  tasks: 
  - name: install webservers on ubuntu
    apt: 
      name: apache2
      state: present
    notify: restartwevservers

  - name: copy dynamic file into all my ubuntu nodes
    template: 
      src: myindex.j2
      dest: /var/www/html/index.
    notify: restartwevservers
  
  handlers: 
  - name: restartwevservers
    service: 
      name: apache2
      state: restarted